/**
 * Mock task data with Japanese content for UI development and screenshots
 */

import type { Task } from "../shared/todoist/schema";

export const MOCK_TASKS: Task[] = [
	// Top-level goal with high priority
	{
		id: "1",
		projectId: "project1",
		content: "アプリケーションのフルリプレイス @goal",
		description: "",
		isCompleted: false,
		labels: ["goal"],
		parentId: null,
		order: 1,
		priority: 4,
		due: {
			date: "2025-12-31",
			string: "Dec 31",
			lang: "ja",
			isRecurring: false,
		},
		url: "https://todoist.com/showTask?id=1",
		commentCount: 0,
		createdAt: "2025-01-01T00:00:00Z",
		creatorId: "user1",
	},
	// Child task under main goal
	{
		id: "2",
		projectId: "project1",
		content: "フロントエンド設計 @task",
		description: "",
		isCompleted: false,
		labels: ["task"],
		parentId: "1",
		order: 1,
		priority: 3,
		due: {
			date: "2025-11-25",
			string: "Nov 25",
			lang: "ja",
			isRecurring: false,
		},
		url: "https://todoist.com/showTask?id=2",
		commentCount: 2,
		createdAt: "2025-01-05T00:00:00Z",
		creatorId: "user1",
	},
	// Grandchild task
	{
		id: "3",
		projectId: "project1",
		content: "Reactコンポーネント実装 @task",
		description: "",
		isCompleted: false,
		labels: ["task"],
		parentId: "2",
		order: 1,
		priority: 3,
		due: null,
		url: "https://todoist.com/showTask?id=3",
		commentCount: 0,
		createdAt: "2025-01-10T00:00:00Z",
		creatorId: "user1",
	},
	// Another child task
	{
		id: "4",
		projectId: "project1",
		content: "バックエンドAPI開発 @task",
		description: "",
		isCompleted: false,
		labels: ["task"],
		parentId: "1",
		order: 2,
		priority: 2,
		due: {
			date: "2025-12-01",
			string: "Dec 1",
			lang: "ja",
			isRecurring: false,
		},
		url: "https://todoist.com/showTask?id=4",
		commentCount: 1,
		createdAt: "2025-01-05T00:00:00Z",
		creatorId: "user1",
	},
	// Second top-level goal with dependency label
	{
		id: "5",
		projectId: "project1",
		content: "データベース最適化 @goal",
		description: "",
		isCompleted: false,
		labels: ["goal", "dep-アプリケーションのフルリプレイス"],
		parentId: null,
		order: 2,
		priority: 2,
		due: {
			date: "2025-11-30",
			string: "Nov 30",
			lang: "ja",
			isRecurring: false,
		},
		url: "https://todoist.com/showTask?id=5",
		commentCount: 0,
		createdAt: "2025-01-15T00:00:00Z",
		creatorId: "user1",
	},
	// Task under dependency goal
	{
		id: "6",
		projectId: "project1",
		content: "インデックス追加 @task",
		description: "",
		isCompleted: false,
		labels: ["task"],
		parentId: "5",
		order: 1,
		priority: 2,
		due: null,
		url: "https://todoist.com/showTask?id=6",
		commentCount: 0,
		createdAt: "2025-01-16T00:00:00Z",
		creatorId: "user1",
	},
	// Simple top-level task
	{
		id: "7",
		projectId: "project1",
		content: "ドキュメント更新 @task",
		description: "",
		isCompleted: false,
		labels: ["task"],
		parentId: null,
		order: 3,
		priority: 1,
		due: null,
		url: "https://todoist.com/showTask?id=7",
		commentCount: 0,
		createdAt: "2025-01-20T00:00:00Z",
		creatorId: "user1",
	},
	// Third goal
	{
		id: "8",
		projectId: "project1",
		content: "パフォーマンス改善 @goal",
		description: "",
		isCompleted: false,
		labels: ["goal"],
		parentId: null,
		order: 4,
		priority: 3,
		due: {
			date: "2025-12-15",
			string: "Dec 15",
			lang: "ja",
			isRecurring: false,
		},
		url: "https://todoist.com/showTask?id=8",
		commentCount: 3,
		createdAt: "2025-01-25T00:00:00Z",
		creatorId: "user1",
	},
	// Multiple level nesting
	{
		id: "9",
		projectId: "project1",
		content: "フロントエンド最適化 @task",
		description: "",
		isCompleted: false,
		labels: ["task"],
		parentId: "8",
		order: 1,
		priority: 3,
		due: null,
		url: "https://todoist.com/showTask?id=9",
		commentCount: 0,
		createdAt: "2025-01-26T00:00:00Z",
		creatorId: "user1",
	},
	{
		id: "10",
		projectId: "project1",
		content: "コード分割実装 @task",
		description: "",
		isCompleted: false,
		labels: ["task"],
		parentId: "9",
		order: 1,
		priority: 3,
		due: null,
		url: "https://todoist.com/showTask?id=10",
		commentCount: 0,
		createdAt: "2025-01-27T00:00:00Z",
		creatorId: "user1",
	},
];
